# Change these first
owner: creadi # Your GitHub organization or username
repo: emmalife-upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: www.emmalife.ch
    url: https://www.emmalife.ch
    assignees:
      - christopheschwyzer
  - name: emmalife.ch
    url: https://emmalife.ch
    assignees:
      - christopheschwyzer
  - name: Life API
    method: POST
    url: https://dev.api.life.creadi.ch
    assignees:
      - MarijaStojanovic
  - name: Life API - Short link
    url: https://dev.api.life.creadi.ch/sl
    method: POST
    headers:
      - 'Content-Type: application/json'
    body: '{"url": "https://foo.bar"}'
    assignees:
      - MarijaStojanovic
  - name: Validation API
    method: POST
    url: https://dev.api.life.creadi.ch/services/validators
    assignees:
      - MarijaStojanovic
  - name: Comparison API
    method: POST
    url: https://life-comparison.vercel.app
    assignees:
      - MarijaStojanovic

assignees: # Users to assign downtime issues (optional)
  - worzst

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /emmalife-upptime
  logoUrl: https://emmalife.ch/logo.svg
  favicon: https://emmalife.ch/favicon-32x32.png
  name: EmmaLife Status
  introTitle: '**EmmaLife** uptime monitor and status page.'
  introMessage: ''
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
