# Change these first
owner: creadi # Your GitHub organization or username
repo: emmalife-upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: www.emmalife.ch
    url: https://www.emmalife.ch
    icon: https://www.emmalife.ch/favicon.ico

  - name: emmalife.ch
    url: https://emmalife.ch
    icon: https://www.emmalife.ch/favicon.ico

  - name: Life API - Quotes
    url: https://api.life.creadi.ch/life/quotes
    icon: https://www.emmalife.ch/favicon.ico
    method: POST
    headers:
      - 'Content-Type: application/json'
    body: '{"dateOfBirth": "2000-04-21","gender": "F","insuredSum": 100000,"smoker": true,"startDate": "2021-04-21"}'

  - name: Life API - Short link
    url: https://api.life.creadi.ch/sl
    icon: https://www.emmalife.ch/favicon.ico
    method: POST
    headers:
      - 'Content-Type: application/json'
    body: '{"url": "https://foo.bar"}'

  - name: Validation API
    icon: https://www.emmalife.ch/favicon.ico
    url: https://api.life.creadi.ch/services/validators/email?email=foo@bar.ch
    method: GET

assignees: # Users to assign downtime issues (optional)
  - worzst

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /emmalife-upptime
  logoUrl: https://emmalife.ch/logo.svg
  favicon: https://emmalife.ch/favicon-32x32.png
  name: EmmaLife Status
  introTitle: '**EmmaLife** uptime monitor and status page.'
  introMessage: ''
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

user-agent: christopheschwyzer

i18n: footer: EmmaLife is a platform by [Creadi AG](https://creadi.ch), the insurtech startup of Pax. We sell life insurance online. As an EmmaLife customer, you benefit from transparent products, fair prices and flexible contracts without paperwork. More at [emmalife.ch](https://emmalife.ch).
