# Change these first
owner: creadi # Your GitHub organization or username
repo: emmalife-upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: www.emmlife.ch
    url: https://www.emmlife.ch
    icon: https://www.emmalife.ch/favicon.ico
  - name: emmlife.ch
    url: https://emmalife.ch
    icon: https://emmalife.ch/favicon.ico

assignees: # Users to assign downtime issues (optional)
  - worzst

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /emmalife-upptime
  logoUrl: https://emmalife.ch/logo.svg
  name: EmmaLife Status
  introTitle: '**EmmaLife** uptime monitor and status page.'
  introMessage: 'Status'
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
